/* --- */

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Exam' AND COLUMN_NAME = 'MaxMins')
BEGIN
ALTER TABLE dbo.Exam ADD
  MaxMins int NOT NULL CONSTRAINT DF_Exam_MaxMins DEFAULT 0
END
GO

/* --- */