//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QScore.lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QScore.lang.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acción.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Búsqueda Avanzada.
        /// </summary>
        public static string AdvancedSearch {
            get {
                return ResourceManager.GetString("AdvancedSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permitir auto-inscripción.
        /// </summary>
        public static string AllowSelfEnroll {
            get {
                return ResourceManager.GetString("AllowSelfEnroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y.
        /// </summary>
        public static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicado.
        /// </summary>
        public static string Applied {
            get {
                return ResourceManager.GetString("Applied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignar.
        /// </summary>
        public static string Assign {
            get {
                return ResourceManager.GetString("Assign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regresar.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entre.
        /// </summary>
        public static string Between {
            get {
                return ResourceManager.GetString("Between", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloqueado.
        /// </summary>
        public static string Blocked {
            get {
                return ResourceManager.GetString("Blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tiene permisos suficientes para llevar a cabo esta operación..
        /// </summary>
        public static string CannotPerformCommand {
            get {
                return ResourceManager.GetString("CannotPerformCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede eliminar..
        /// </summary>
        public static string CantDelete {
            get {
                return ResourceManager.GetString("CantDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catálogos.
        /// </summary>
        public static string Catalogs {
            get {
                return ResourceManager.GetString("Catalogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los cambios han sido guardados..
        /// </summary>
        public static string ChangesHaveBeenSaved {
            get {
                return ResourceManager.GetString("ChangesHaveBeenSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los cambios no han sido guardados.
        /// </summary>
        public static string ChangesNotSaved {
            get {
                return ResourceManager.GetString("ChangesNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limpiar.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración.
        /// </summary>
        public static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea continuar?.
        /// </summary>
        public static string ConfirmAction {
            get {
                return ResourceManager.GetString("ConfirmAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro de que desea eliminar el registro? Esta operación es irreversible..
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contenga.
        /// </summary>
        public static string Contains {
            get {
                return ResourceManager.GetString("Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuar.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respuesta Correcta.
        /// </summary>
        public static string CorrectAnswer {
            get {
                return ResourceManager.GetString("CorrectAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opción Correcta.
        /// </summary>
        public static string CorrectOption {
            get {
                return ResourceManager.GetString("CorrectOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña Actual.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo de Datos.
        /// </summary>
        public static string DataGroup {
            get {
                return ResourceManager.GetString("DataGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El grupo de datos debe estar vacio..
        /// </summary>
        public static string DataGroupMustBeEmpty {
            get {
                return ResourceManager.GetString("DataGroupMustBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Aplicación.
        /// </summary>
        public static string DateCompleted {
            get {
                return ResourceManager.GetString("DateCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha/Hora.
        /// </summary>
        public static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Índice de Dificultad.
        /// </summary>
        public static string DifficultyIndex {
            get {
                return ResourceManager.GetString("DifficultyIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Índice de Discriminación.
        /// </summary>
        public static string DiscriminationIndex {
            get {
                return ResourceManager.GetString("DiscriminationIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Aplica.
        /// </summary>
        public static string DoesntApply {
            get {
                return ResourceManager.GetString("DoesntApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        public static string DoSearch {
            get {
                return ResourceManager.GetString("DoSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione.
        /// </summary>
        public static string DoSelect {
            get {
                return ResourceManager.GetString("DoSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descargar.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descargar Formato.
        /// </summary>
        public static string DownloadLayout {
            get {
                return ResourceManager.GetString("DownloadLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese un valor entero entre %%0 y %%1.
        /// </summary>
        public static string EnterIntegerBetweenXandY {
            get {
                return ResourceManager.GetString("EnterIntegerBetweenXandY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese un valor entre %%0 y %%1.
        /// </summary>
        public static string EnterValueBetweenXandY {
            get {
                return ResourceManager.GetString("EnterValueBetweenXandY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicación de Exámenes.
        /// </summary>
        public static string EvalApplication {
            get {
                return ResourceManager.GetString("EvalApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examen.
        /// </summary>
        public static string Exam {
            get {
                return ResourceManager.GetString("Exam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completo.
        /// </summary>
        public static string Exam_Complete {
            get {
                return ResourceManager.GetString("Exam_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Aprobado.
        /// </summary>
        public static string Exam_Failed {
            get {
                return ResourceManager.GetString("Exam_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incompleto.
        /// </summary>
        public static string Exam_Incomplete {
            get {
                return ResourceManager.GetString("Exam_Incomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprobado.
        /// </summary>
        public static string Exam_Passed {
            get {
                return ResourceManager.GetString("Exam_Passed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pendiente.
        /// </summary>
        public static string Exam_Pending {
            get {
                return ResourceManager.GetString("Exam_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examen(es).
        /// </summary>
        public static string Exam_s {
            get {
                return ResourceManager.GetString("Exam_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examen asignado..
        /// </summary>
        public static string ExamAssigned {
            get {
                return ResourceManager.GetString("ExamAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este examen ya ha sido aplicado, no se pueden modificar las secciones (reactivos, temas)..
        /// </summary>
        public static string ExamHasBeenUsedCantBeEdited {
            get {
                return ResourceManager.GetString("ExamHasBeenUsedCantBeEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exámenes.
        /// </summary>
        public static string Exams {
            get {
                return ResourceManager.GetString("Exams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exámenes a Asignar.
        /// </summary>
        public static string ExamsToAssign {
            get {
                return ResourceManager.GetString("ExamsToAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El examen no se asignó..
        /// </summary>
        public static string ExamWasNotAssigned {
            get {
                return ResourceManager.GetString("ExamWasNotAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportar.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificador Externo.
        /// </summary>
        public static string ExternalIdentifier {
            get {
                return ResourceManager.GetString("ExternalIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo.
        /// </summary>
        public static string Field {
            get {
                return ResourceManager.GetString("Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo(s).
        /// </summary>
        public static string Field_s {
            get {
                return ResourceManager.GetString("Field_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campos.
        /// </summary>
        public static string Fields {
            get {
                return ResourceManager.GetString("Fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secuencia de Campos.
        /// </summary>
        public static string FieldSequence {
            get {
                return ResourceManager.GetString("FieldSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campos a Exportar.
        /// </summary>
        public static string FieldsToExport {
            get {
                return ResourceManager.GetString("FieldsToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtros.
        /// </summary>
        public static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminar.
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primera Página.
        /// </summary>
        public static string FirstPage {
            get {
                return ResourceManager.GetString("FirstPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkbox.
        /// </summary>
        public static string fld_Checkbox {
            get {
                return ResourceManager.GetString("fld_Checkbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string fld_Date {
            get {
                return ResourceManager.GetString("fld_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo Electrónico.
        /// </summary>
        public static string fld_Email {
            get {
                return ResourceManager.GetString("fld_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número con Decimales.
        /// </summary>
        public static string fld_Float {
            get {
                return ResourceManager.GetString("fld_Float", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número Entero.
        /// </summary>
        public static string fld_Integer {
            get {
                return ResourceManager.GetString("fld_Integer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etiqueta.
        /// </summary>
        public static string fld_Label {
            get {
                return ResourceManager.GetString("fld_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texto Multilínea.
        /// </summary>
        public static string fld_Multitext {
            get {
                return ResourceManager.GetString("fld_Multitext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opciones Fijas.
        /// </summary>
        public static string fld_Options {
            get {
                return ResourceManager.GetString("fld_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texto Simple.
        /// </summary>
        public static string fld_SimpleText {
            get {
                return ResourceManager.GetString("fld_SimpleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barra de Desplazamiento.
        /// </summary>
        public static string fld_Slider {
            get {
                return ResourceManager.GetString("fld_Slider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Árbol de Selección.
        /// </summary>
        public static string fld_Tree {
            get {
                return ResourceManager.GetString("fld_Tree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si / No.
        /// </summary>
        public static string fld_YesNo {
            get {
                return ResourceManager.GetString("fld_YesNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre Completo.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permitir Acceso.
        /// </summary>
        public static string GrantPermission {
            get {
                return ResourceManager.GetString("GrantPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayuda.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificador.
        /// </summary>
        public static string Identifier {
            get {
                return ResourceManager.GetString("Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importar.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactivo.
        /// </summary>
        public static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de Usuario y/o Contraseña incorrectos.
        /// </summary>
        public static string IncorrectCredentials {
            get {
                return ResourceManager.GetString("IncorrectCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese sus datos para iniciar sesión.
        /// </summary>
        public static string InputLogin {
            get {
                return ResourceManager.GetString("InputLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrucción.
        /// </summary>
        public static string Instruction {
            get {
                return ResourceManager.GetString("Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrucciones.
        /// </summary>
        public static string Instructions {
            get {
                return ResourceManager.GetString("Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dato inválido.
        /// </summary>
        public static string InvalidData {
            get {
                return ResourceManager.GetString("InvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Inválida.
        /// </summary>
        public static string InvalidDate {
            get {
                return ResourceManager.GetString("InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo electrónico inválido.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña Inválida.
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invisible al usuario.
        /// </summary>
        public static string InvisibleToSelf {
            get {
                return ResourceManager.GetString("InvisibleToSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sea.
        /// </summary>
        public static string Is {
            get {
                return ResourceManager.GetString("Is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sea entre.
        /// </summary>
        public static string IsBetween {
            get {
                return ResourceManager.GetString("IsBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sea mayor o igual a.
        /// </summary>
        public static string IsGreaterOrEqualTo {
            get {
                return ResourceManager.GetString("IsGreaterOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sea menor o igual a.
        /// </summary>
        public static string IsSmallerOrEqualTo {
            get {
                return ResourceManager.GetString("IsSmallerOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        public static string Kind {
            get {
                return ResourceManager.GetString("Kind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anterior.
        /// </summary>
        public static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido Paterno.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Última Página.
        /// </summary>
        public static string LastPage {
            get {
                return ResourceManager.GetString("LastPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para importar requiere utilizar el formato correspondiente..
        /// </summary>
        public static string LayoutNeeded {
            get {
                return ResourceManager.GetString("LayoutNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alta.
        /// </summary>
        public static string log_Create {
            get {
                return ResourceManager.GetString("log_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baja.
        /// </summary>
        public static string log_Delete {
            get {
                return ResourceManager.GetString("log_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambio.
        /// </summary>
        public static string log_Update {
            get {
                return ResourceManager.GetString("log_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar Sesión.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceso fallido al sistema.
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio de Sesión.
        /// </summary>
        public static string LoginPage {
            get {
                return ResourceManager.GetString("LoginPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar Sesión.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La sesión ha expirado, ingrese nuevamente..
        /// </summary>
        public static string LostSession {
            get {
                return ResourceManager.GetString("LostSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        public static string MainPage {
            get {
                return ResourceManager.GetString("MainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calificación Mínima Aprobatoria.
        /// </summary>
        public static string MasteryScore {
            get {
                return ResourceManager.GetString("MasteryScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Límite (en minutos) del examen.
        /// </summary>
        public static string MaxMins {
            get {
                return ResourceManager.GetString("MaxMins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero Máximo de Preguntas.
        /// </summary>
        public static string MaxNumberOfQuestions {
            get {
                return ResourceManager.GetString("MaxNumberOfQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Máximo.
        /// </summary>
        public static string MaxValue {
            get {
                return ResourceManager.GetString("MaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar Campos.
        /// </summary>
        public static string mdl_Add_Fields {
            get {
                return ResourceManager.GetString("mdl_Add_Fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar Usuarios.
        /// </summary>
        public static string mdl_Add_User {
            get {
                return ResourceManager.GetString("mdl_Add_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catálogos del Sistema.
        /// </summary>
        public static string mdl_Catalogs {
            get {
                return ResourceManager.GetString("mdl_Catalogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administración de Campos.
        /// </summary>
        public static string mdl_Datafields_Administration {
            get {
                return ResourceManager.GetString("mdl_Datafields_Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar Campos.
        /// </summary>
        public static string mdl_Delete_Fields {
            get {
                return ResourceManager.GetString("mdl_Delete_Fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar Usuarios.
        /// </summary>
        public static string mdl_Delete_User {
            get {
                return ResourceManager.GetString("mdl_Delete_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Campos.
        /// </summary>
        public static string mdl_Edit_Fields {
            get {
                return ResourceManager.GetString("mdl_Edit_Fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Contraseñas.
        /// </summary>
        public static string mdl_Edit_Passwords {
            get {
                return ResourceManager.GetString("mdl_Edit_Passwords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Permisos.
        /// </summary>
        public static string mdl_Edit_Permissions {
            get {
                return ResourceManager.GetString("mdl_Edit_Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Mis Datos.
        /// </summary>
        public static string mdl_Edit_Self_Info {
            get {
                return ResourceManager.GetString("mdl_Edit_Self_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar Contraseña.
        /// </summary>
        public static string mdl_Edit_Self_Password {
            get {
                return ResourceManager.GetString("mdl_Edit_Self_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Usuarios.
        /// </summary>
        public static string mdl_Edit_User {
            get {
                return ResourceManager.GetString("mdl_Edit_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignación de Exámenes.
        /// </summary>
        public static string mdl_Eval_Assign {
            get {
                return ResourceManager.GetString("mdl_Eval_Assign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catálogo de Exámenes.
        /// </summary>
        public static string mdl_Eval_Exam_Catalog {
            get {
                return ResourceManager.GetString("mdl_Eval_Exam_Catalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importación de Exámenes.
        /// </summary>
        public static string mdl_Eval_Import_Exams {
            get {
                return ResourceManager.GetString("mdl_Eval_Import_Exams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importación de Resultados.
        /// </summary>
        public static string mdl_Eval_Import_Results {
            get {
                return ResourceManager.GetString("mdl_Eval_Import_Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catálogo de Reactivos.
        /// </summary>
        public static string mdl_Eval_Question_Catalog {
            get {
                return ResourceManager.GetString("mdl_Eval_Question_Catalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reportes.
        /// </summary>
        public static string mdl_Eval_Reports {
            get {
                return ResourceManager.GetString("mdl_Eval_Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicación de Exámenes de Usuarios.
        /// </summary>
        public static string mdl_Eval_Solve_User {
            get {
                return ResourceManager.GetString("mdl_Eval_Solve_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catálogo de Temas.
        /// </summary>
        public static string mdl_Eval_Theme_Catalog {
            get {
                return ResourceManager.GetString("mdl_Eval_Theme_Catalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exámenes.
        /// </summary>
        public static string mdl_Evaluation {
            get {
                return ResourceManager.GetString("mdl_Evaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportación de Usuarios.
        /// </summary>
        public static string mdl_Export_Users {
            get {
                return ResourceManager.GetString("mdl_Export_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importación de Usuarios.
        /// </summary>
        public static string mdl_Import_Users {
            get {
                return ResourceManager.GetString("mdl_Import_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitácora del Sistema.
        /// </summary>
        public static string mdl_Log_Access {
            get {
                return ResourceManager.GetString("mdl_Log_Access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catálogo de Roles.
        /// </summary>
        public static string mdl_Role_Catalog {
            get {
                return ResourceManager.GetString("mdl_Role_Catalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administración de Usuarios.
        /// </summary>
        public static string mdl_User_Administration {
            get {
                return ResourceManager.GetString("mdl_User_Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Mínimo.
        /// </summary>
        public static string MinValue {
            get {
                return ResourceManager.GetString("MinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necesita completar todos los datos.
        /// </summary>
        public static string MissingFields {
            get {
                return ResourceManager.GetString("MissingFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar los siguientes datos:.
        /// </summary>
        public static string MissingTheseFields {
            get {
                return ResourceManager.GetString("MissingTheseFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módulo.
        /// </summary>
        public static string Module {
            get {
                return ResourceManager.GetString("Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido Materno.
        /// </summary>
        public static string MotherLastName {
            get {
                return ResourceManager.GetString("MotherLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe contestar totas las preguntas..
        /// </summary>
        public static string MustAnswerEveryQuestion {
            get {
                return ResourceManager.GetString("MustAnswerEveryQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deben haber por lo menos dos opciones de respuesta..
        /// </summary>
        public static string MustHaveAtLeastTwoOptions {
            get {
                return ResourceManager.GetString("MustHaveAtLeastTwoOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar un archivo..
        /// </summary>
        public static string MustSelectAFile {
            get {
                return ResourceManager.GetString("MustSelectAFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar por lo menos una opción correcta..
        /// </summary>
        public static string MustSelectAtLeastOneCorrectAnswer {
            get {
                return ResourceManager.GetString("MustSelectAtLeastOneCorrectAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mi Cuenta.
        /// </summary>
        public static string MyAccount {
            get {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string NA {
            get {
                return ResourceManager.GetString("NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva Contraseña.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siguiente.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ninguno.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin Padre.
        /// </summary>
        public static string NoParent {
            get {
                return ResourceManager.GetString("NoParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay examenes pendientes de aplicar..
        /// </summary>
        public static string NoPendingExams {
            get {
                return ResourceManager.GetString("NoPendingExams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El número de respuestas es distinto..
        /// </summary>
        public static string NumberOfAnswersDoesntMatch {
            get {
                return ResourceManager.GetString("NumberOfAnswersDoesntMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero de Preguntas.
        /// </summary>
        public static string NumberOfQuestions {
            get {
                return ResourceManager.GetString("NumberOfQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opción.
        /// </summary>
        public static string Option {
            get {
                return ResourceManager.GetString("Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opciones.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to o.
        /// </summary>
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Página.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Página(s).
        /// </summary>
        public static string Page_s {
            get {
                return ResourceManager.GetString("Page_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Páginas.
        /// </summary>
        public static string Pages {
            get {
                return ResourceManager.GetString("Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Página %%0 de %%1.
        /// </summary>
        public static string PageXofY {
            get {
                return ResourceManager.GetString("PageXofY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Padre.
        /// </summary>
        public static string Parent {
            get {
                return ResourceManager.GetString("Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tema Padre.
        /// </summary>
        public static string ParentTheme {
            get {
                return ResourceManager.GetString("ParentTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña y confirmación de contraseña deben ser iguales.
        /// </summary>
        public static string PasswordConfirmationDoesntMatch {
            get {
                return ResourceManager.GetString("PasswordConfirmationDoesntMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La persona tiene asignado y pendiente el examen..
        /// </summary>
        public static string PendingExamExists {
            get {
                return ResourceManager.GetString("PendingExamExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espere un momento por favor.
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puntos.
        /// </summary>
        public static string Points {
            get {
                return ResourceManager.GetString("Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprimir.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceso Completado.
        /// </summary>
        public static string ProcessCompleted {
            get {
                return ResourceManager.GetString("ProcessCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reactivo.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reactivo(s).
        /// </summary>
        public static string Question_s {
            get {
                return ResourceManager.GetString("Question_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La pregunta ya existe..
        /// </summary>
        public static string QuestionAlreadyExists {
            get {
                return ResourceManager.GetString("QuestionAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este reactivo ya ha sido aplicado, no puede ser modificado..
        /// </summary>
        public static string QuestionHasBeenUsedCantBeEdited {
            get {
                return ResourceManager.GetString("QuestionHasBeenUsedCantBeEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este reactivo ya ha sido utilizado, si hace algún cambio, se generará una copia de este reactivo para guardarlo como histórico..
        /// </summary>
        public static string QuestionHasBeenUsedWillBeCloned {
            get {
                return ResourceManager.GetString("QuestionHasBeenUsedWillBeCloned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reactivos.
        /// </summary>
        public static string Questions {
            get {
                return ResourceManager.GetString("Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preguntas por página.
        /// </summary>
        public static string QuestionsPerPage {
            get {
                return ResourceManager.GetString("QuestionsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Búsqueda Rápida.
        /// </summary>
        public static string QuickSearch {
            get {
                return ResourceManager.GetString("QuickSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro.
        /// </summary>
        public static string Record {
            get {
                return ResourceManager.GetString("Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registros.
        /// </summary>
        public static string Records {
            get {
                return ResourceManager.GetString("Records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El registro &apos;%%0&apos; ya existe..
        /// </summary>
        public static string RecordXTaken {
            get {
                return ResourceManager.GetString("RecordXTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Registro.
        /// </summary>
        public static string RegistryDate {
            get {
                return ResourceManager.GetString("RegistryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repita para confirmar.
        /// </summary>
        public static string RepeatToConfirm {
            get {
                return ResourceManager.GetString("RepeatToConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requerido.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los campos requeridos no fueron capturados o tienen datos inválidos..
        /// </summary>
        public static string RequiredFieldsMissing {
            get {
                return ResourceManager.GetString("RequiredFieldsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar contraseña a.
        /// </summary>
        public static string ResetPasswordTo {
            get {
                return ResourceManager.GetString("ResetPasswordTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denegar Acceso.
        /// </summary>
        public static string RevokePermission {
            get {
                return ResourceManager.GetString("RevokePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Al marcar ambas opciones, denegar será el que se utilice.
        /// </summary>
        public static string RevokeSupersedesGrant {
            get {
                return ResourceManager.GetString("RevokeSupersedesGrant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrador.
        /// </summary>
        public static string role_Administrator {
            get {
                return ResourceManager.GetString("role_Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceso Completo.
        /// </summary>
        public static string role_Full_Access {
            get {
                return ResourceManager.GetString("role_Full_Access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol(es).
        /// </summary>
        public static string Role_s {
            get {
                return ResourceManager.GetString("Role_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        public static string role_User {
            get {
                return ResourceManager.GetString("role_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raíz.
        /// </summary>
        public static string Root {
            get {
                return ResourceManager.GetString("Root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fila.
        /// </summary>
        public static string Row {
            get {
                return ResourceManager.GetString("Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fila importada.
        /// </summary>
        public static string RowImported {
            get {
                return ResourceManager.GetString("RowImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calificación.
        /// </summary>
        public static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Búsqueda.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sección.
        /// </summary>
        public static string Section {
            get {
                return ResourceManager.GetString("Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sección(es).
        /// </summary>
        public static string Section_s {
            get {
                return ResourceManager.GetString("Section_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secciones.
        /// </summary>
        public static string Sections {
            get {
                return ResourceManager.GetString("Sections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respuesta Seleccionada.
        /// </summary>
        public static string SelectedAnswer {
            get {
                return ResourceManager.GetString("SelectedAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selección de.
        /// </summary>
        public static string SelectionOf {
            get {
                return ResourceManager.GetString("SelectionOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El examen es de autoinscripción y la persona no ha accedido..
        /// </summary>
        public static string SelfEnrollExamNotAttempted {
            get {
                return ResourceManager.GetString("SelfEnrollExamNotAttempted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secuencia.
        /// </summary>
        public static string Sequence {
            get {
                return ResourceManager.GetString("Sequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sesión.
        /// </summary>
        public static string Session {
            get {
                return ResourceManager.GetString("Session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sesión Cerrada.
        /// </summary>
        public static string SessionClosed {
            get {
                return ResourceManager.GetString("SessionClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sesión Expirada.
        /// </summary>
        public static string SessionExpired {
            get {
                return ResourceManager.GetString("SessionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sesión Iniciada.
        /// </summary>
        public static string SessionStarted {
            get {
                return ResourceManager.GetString("SessionStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar Búsqueda Avanzada.
        /// </summary>
        public static string ShowAdvancedSearch {
            get {
                return ResourceManager.GetString("ShowAdvancedSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrando %%0 de %%1.
        /// </summary>
        public static string ShowingXofY {
            get {
                return ResourceManager.GetString("ShowingXofY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar preguntas en orden aleatorio.
        /// </summary>
        public static string ShuffleQuestions {
            get {
                return ResourceManager.GetString("ShuffleQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración del Sistema.
        /// </summary>
        public static string SystemConfiguration {
            get {
                return ResourceManager.GetString("SystemConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tema.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tema(s).
        /// </summary>
        public static string Theme_s {
            get {
                return ResourceManager.GetString("Theme_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temas.
        /// </summary>
        public static string Themes {
            get {
                return ResourceManager.GetString("Themes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tema %%0 ya existe en el examen..
        /// </summary>
        public static string ThemeXAlreadyExists {
            get {
                return ResourceManager.GetString("ThemeXAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El examen ya incluye un tema padre o hijo (&apos;%%1&apos;) del tema &apos;%%0&apos;..
        /// </summary>
        public static string ThemeXParentChildYAlreadyExists {
            get {
                return ResourceManager.GetString("ThemeXParentChildYAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha terminado el tiempo para la aplicación del examen..
        /// </summary>
        public static string TimesUp {
            get {
                return ResourceManager.GetString("TimesUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizar.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargar.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario no existe..
        /// </summary>
        public static string UserDoesntExist {
            get {
                return ResourceManager.GetString("UserDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario &apos;%%0&apos; ya existe..
        /// </summary>
        public static string UsernameTaken {
            get {
                return ResourceManager.GetString("UsernameTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol de usuario.
        /// </summary>
        public static string UserRole {
            get {
                return ResourceManager.GetString("UserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espere un momento.
        /// </summary>
        public static string WaitAMoment {
            get {
                return ResourceManager.GetString("WaitAMoment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se utilizará si es cero.
        /// </summary>
        public static string WontBeUsedIfZero {
            get {
                return ResourceManager.GetString("WontBeUsedIfZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El archivo que intentó cargar no corresponde con los encabezados esperados, por favor descargue de nueva cuenta el formato..
        /// </summary>
        public static string WrongLayout {
            get {
                return ResourceManager.GetString("WrongLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se asignarán %%0 exámenes a %%1 usuarios..
        /// </summary>
        public static string XExamsWillBeAssignedToYUsers {
            get {
                return ResourceManager.GetString("XExamsWillBeAssignedToYUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se exportarán %%0 usuarios..
        /// </summary>
        public static string XUsersWillBeExported {
            get {
                return ResourceManager.GetString("XUsersWillBeExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
